name: 'Github Runner action'
description: 'Run Github tasks'
inputs:
  token:
    description: 'A repo scoped GitHub Personal Access Token'
    required: true
  repository:
    description: 'The full name of the repository to send the dispatch.'
    default: ${{ github.repository }}
  component:
    description: 'Status component'
  commit:
    description: 'Status commit'
  status:
    description: '"error" | "success" | "cancelled"'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: dist/index.js
branding:
  icon: 'target'
  color: 'gray-dark'
