name: 'Github Dispatcher'
description: 'Create Github dispatch events'
inputs:
  token:
    description: 'A repo scoped GitHub Personal Access Token'
    required: true
  repository:
    description: 'The full name of the repository to send the dispatch.'
    default: ${{ github.repository }}
  component:
    description: 'Name/Version of component to dispatch.'
    default:
  arguments:
    description: 'Additional arguments.'
    default:
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'target'
  color: 'gray-dark'
