name: "Github Dispatcher"
description: "Create Github dispatch events"
inputs:
  token:
    description: "A repo scoped GitHub Personal Access Token"
    default: ${{ github.token }}
  repository:
    description: "The full name of the repository to send the dispatch."
    default: ${{ github.repository }}
  last_commit:
    description: "The last commit to compare with."
    default: ${{ github.event.before }}
  mode:
    description: "Workflow mode: (manual, git, alias)"
    default: git
  component:
    description: "Name/Version of component to dispatch."
    default:
  arguments:
    description: "Additional arguments."
    default:
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "target"
  color: "gray-dark"
